# Generated by Django 4.2.5 on 2023-09-28 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(null=True)),
                ('name', models.CharField()),
                ('winner', models.IntegerField(choices=[(0, '進行中'), (1, '村人'), (2, '人狼'), (3, '妖孤'), (4, '恋人'), (5, '全滅'), (6, '廃村')])),
                ('gm', models.BooleanField()),
                ('wish', models.BooleanField()),
                ('death_note', models.BooleanField()),
                ('pattern', models.CharField()),
                ('log', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.IntegerField()),
                ('name', models.CharField()),
                ('profile', models.CharField(blank=True)),
                ('icon', models.IntegerField()),
                ('role', models.IntegerField(choices=[(0, '未決定'), (1, '村人'), (2, '人狼'), (3, '占い師'), (4, '預言者'), (5, '霊能者'), (6, '狩人'), (7, '共有者'), (8, '猫又'), (9, '狂人'), (10, '狂信者'), (11, '聴覚狂人'), (12, '妖狐'), (13, '背徳者')])),
                ('is_love', models.BooleanField(default=False)),
                ('wish', models.IntegerField(choices=[(0, '未決定'), (1, '村人'), (2, '人狼'), (3, '占い師'), (4, '預言者'), (5, '霊能者'), (6, '狩人'), (7, '共有者'), (8, '猫又'), (9, '狂人'), (10, '狂信者'), (11, '聴覚狂人'), (12, '妖狐'), (13, '背徳者')])),
                ('is_suddendeath', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField()),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.log')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.IntegerField()),
                ('is_player', models.BooleanField()),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.log')),
            ],
        ),
    ]
